GET http://3.209.155.46:3000/api/users
GET http://3.209.155.46:3000/api/posts
GET http://3.209.155.46:3000/api/categories

###

GET http://3.209.155.46:3000/api/users?listado=true


### 

GET http://3.209.155.46:3000/api/users/2?relations=true

###
POST http://3.209.155.46:3000/api/users
Content-Type: application/json
{
    "user_id":3,
    "user_name":"Pepe",
    "address":"calle Botijo 1",
    "phone_number":879453162,
    "gmail":"ElBotijo@gmail.com"
}

POST http://3.209.155.46:3000/api/posts
Content-Type: application/json
{
            "post_id": 1,
            "user_gmail": "correo@gmail.com",
            "post_text": "contenido de la publicacion",
            "post_category": "prueba"
        }
